version: "3.1"
services:
  habitica-discord-bot:
    image: habitica-discord-bot
    container_name: habitica-discord-bot
    build: .
    env_file:
      .env
    restart: always
    ports:
      - 1818:8080
    volumes:
      - ./data:/usr/src/app/data